version: '3.8'

services:
  db:
    image: postgres:14  
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres      
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: nest_db
    ports:
      - '5432:5432' 
    volumes:
      - postgres_data:/var/lib/postgresql/data  


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - db
      
volumes:
  postgres_data:

